name: Build Flipper Application Package (FAP)

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Asteroids FAP
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Build Flipper Application Package
      uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
      id: build-fap
      with:
        app-dir: .

    - name: Upload FAP artifact
      uses: actions/upload-artifact@v4
      with:
        name: asteroids-fap
        path: |
          dist/*.fap
          dist/*.fap.debug
        retention-days: 30

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.fap
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
